# Generated by Django 3.2.4 on 2021-11-14 03:41

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstbl',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(default='-', max_length=50)),
                ('Mobile', models.CharField(default='-', max_length=50)),
                ('Address', models.CharField(default='-', max_length=80)),
                ('Birthday', models.DateField(default='-')),
                ('Joining_date', models.DateField(default='-')),
                ('Profile_pic', models.ImageField(default='-', upload_to='profile_pic')),
                ('adminEmail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Orgnization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userstbl',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(default='-', max_length=50)),
                ('Mobile', models.CharField(default='-', max_length=50)),
                ('Address', models.CharField(default='-', max_length=80)),
                ('Birthday', models.DateField(default='-')),
                ('Joining_date', models.DateField(default='-')),
                ('Profile_pic', models.ImageField(default='-', upload_to='profile_pic')),
                ('userEmail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adminstbl', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Bookstbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Publication', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('AvailableCopies', models.IntegerField()),
                ('IssuedCopies', models.IntegerField()),
                ('TotalCopies', models.IntegerField()),
                ('Book_cover', models.ImageField(default='-', upload_to='book_covers')),
                ('isbook', models.BooleanField()),
                ('Pdf_file', models.FileField(default='-', storage=django.core.files.storage.FileSystemStorage(location='/media/ebook'), upload_to='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adminstbl', verbose_name='')),
            ],
        ),
    ]
