# Generated by Django 3.2.4 on 2021-11-14 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstbl',
            name='isbook',
        ),
        migrations.AddField(
            model_name='bookstbl',
            name='isebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Profile_pic',
            field=models.ImageField(default='-', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2021, 11, 14)),
        ),
    ]
