# Generated by Django 3.2.4 on 2021-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20211115_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstbl',
            name='Pdf_file',
            field=models.FileField(default='-', upload_to='ebook'),
        ),
    ]
