# Generated by Django 4.0.1 on 2022-01-11 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_bookstbl_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 1, 11)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 1, 11)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 1, 11)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 1, 11)),
        ),
    ]
