# Generated by Django 4.0.1 on 2022-01-12 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_adminstbl_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstbl',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 1, 12)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 1, 12)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 1, 12)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 1, 12)),
        ),
    ]
