# Generated by Django 4.0.1 on 2022-01-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_userstbl_gender_alter_adminstbl_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstbl',
            name='Gender',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
