# Generated by Django 4.0.2 on 2022-02-10 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_userstbl_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
    ]
