# Generated by Django 4.0.1 on 2022-02-11 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_adminstbl_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
        migrations.AlterField(
            model_name='adminstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Birthday',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
    ]
